/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rfbsoft;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println("Running….");
        for (int i=0; i <100; i++) {
            System.out.println("Step: "+ i);
            try{
                Thread.sleep(1000);
            }catch (Exception e) {
                System.out.println("Error");
            }
        }

    }
}
